[package]
name = "kaleid-macros"
version = "0.1.0"
edition.workspace = true

[lib]
proc-macro = true

[dependencies]
extension-traits.workspace = true
itertools = "0.14"
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", default-features = false, features = [
  "extra-traits",
  "full",
  "parsing",
  "printing",
  "proc-macro"
] }

[dev-dependencies]
pretty_assertions = "1.4"
